name: Deploy Test
on:
  push:
    branches: 
      - main
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "CONTRIBUTING.md"
      - "LICENSE.txt"
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'FORCE DEPLOY: Bypass safety checks?'
        required: true
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
    
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run all linters
        run: npm run lint:all

      - name: Run all scripts from folder scripts
        env:
          URL_CHECKER_TIMEOUT: ${{ vars.URL_CHECKER_TIMEOUT || '5000' }}
        run: node script/url-checker.js -t $URL_CHECKER_TIMEOUT -d src/posts

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout step
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Set PATH_PREFIX and Build
        env:
          PATH_PREFIX: /${{ github.event.repository.name }}/
        run: npm run prod
        
      - name: Upload static pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy:
    name: Deploy
    needs: [test, build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
      issues: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Create Issues
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_STATUS: ${{ job.status }}
          PAGE_URL: ${{ steps.deployment.outputs.page_url }}
        run: |
          DATE=$(date +'%Y-%m-%d')
          gh issue --repo ${{ github.repository }} \
            create --title "$DATE - Deployment: $DEPLOY_STATUS" --body "URL: $PAGE_URL"

